<?xml version="1.0" encoding="utf-8" ?>
<Project>
    <PropertyGroup>
        <!-- This points to where your game is located on your disk. -->
        <GamePath>C:\Program Files (x86)\Steam\steamapps\common\Gorilla Tag</GamePath>

        <!-- This points to where Gorilla Tag holds it's code -->
        <GameAssemblyPath>$(GamePath)\Gorilla Tag_Data\Managed</GameAssemblyPath>

        <!-- This points to the references needed for BepInEx and MelonLoader -->
        <DependenciesPath>..\Build\Dependencies</DependenciesPath>
    </PropertyGroup>
</Project>
